### ISSUE TITLE
Announcement Page

### ISSUE THREAD

**Issue by bestworks221** [iPhiTech-Applications/iPhiTech-Backend#521]
1. Update button text "Create" to Update/Edit - https://prnt.sc/wZLVb7SzXEcz
2. When trying to edit department and role didn't selected - https://prnt.sc/LQ1ynHXvTRhp

**Comment by ri-bulatao** [comment]
Fix on #531 

- [x]  Update button text "Create" to Update/Edit - https://prnt.sc/wZLVb7SzXEcz
- [x] When trying to edit department and role didn't select - https://prnt.sc/LQ1ynHXvTRhp
